"""Database Products Creation

Revision ID: 605867732820
Revises: f0646ac7ed24
Create Date: 2024-06-26 19:36:34.551382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605867732820'
down_revision: Union[str, None] = 'f0646ac7ed24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UnikalnyjKodProdukta', sa.String(), nullable=True),
    sa.Column('NomerPartii', sa.Integer(), nullable=True),
    sa.Column('DataPartii', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_aggregated', sa.Boolean(), nullable=True),
    sa.Column('aggregated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('assignment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment'], ['shift_assignment.NomerPartii'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
