"""Database shift_assignment Creation

Revision ID: f0646ac7ed24
Revises: 
Create Date: 2024-06-24 19:28:25.615556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0646ac7ed24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('StatusZakrytiya', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('PredstavlenieZadaniyaNaSmenu', sa.String(), nullable=True),
    sa.Column('Liniya', sa.String(), nullable=True),
    sa.Column('Smena', sa.String(), nullable=True),
    sa.Column('Brigada', sa.String(), nullable=True),
    sa.Column('NomerPartii', sa.Integer(), nullable=True),
    sa.Column('DataPartii', sa.TIMESTAMP(), nullable=True),
    sa.Column('Nomenklatura', sa.String(), nullable=True),
    sa.Column('KodEKN', sa.String(), nullable=True),
    sa.Column('IdentifikatorRC', sa.String(), nullable=True),
    sa.Column('DataVremyaNachalaSmeny', sa.TIMESTAMP(), nullable=False),
    sa.Column('DataVremyaOkonchaniyaSmeny', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('DataPartii'),
    sa.UniqueConstraint('NomerPartii')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_assignment')
    # ### end Alembic commands ###
